"""initial studio schema

Revision ID: 9b2744d7f916
Revises: 
Create Date: 2026-07-28 01:26:38.282419
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '9b2744d7f916'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """套用變更。"""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_chapters',
    sa.Column('id', sa.String(length=64), nullable=False, comment='章節 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所屬專案 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='章節序號（專案內唯一）'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='章節標題'),
    sa.Column('summary', sa.Text(), nullable=False, comment='章節摘要'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='腳本原文'),
    sa.Column('condensed_text', sa.Text(), nullable=False, comment='模型精簡後的腳本'),
    sa.Column('status', sa.Enum('draft', 'shooting', 'done', name='chapterstatus', native_enum=False, length=16), nullable=False, comment='章節狀態'),
    sa.Column('shot_count', sa.Integer(), nullable=False, comment='分鏡數量快取；避免列表頁為了顯示數量而 count 子表'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'index', name='uq_studio_chapters_project_index')
    )
    with op.batch_alter_table('studio_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_chapters_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_studio_chapters_status', ['status'], unique=False)
        batch_op.create_index('ix_studio_chapters_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_files',
    sa.Column('id', sa.String(length=64), nullable=False, comment='檔案 ID'),
    sa.Column('file_type', sa.Enum('image', 'video', 'audio', name='filetype', native_enum=False, length=16), nullable=False, comment='檔案類型'),
    sa.Column('storage_key', sa.String(length=1024), nullable=False, comment='物件儲存 key；公開 URL 於執行期組出，不存於資料庫'),
    sa.Column('filename', sa.String(length=512), nullable=False, comment='原始檔名'),
    sa.Column('content_type', sa.String(length=128), nullable=False, comment='MIME type'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='檔案大小（bytes）'),
    sa.Column('width', sa.Integer(), nullable=False, comment='影像寬度（px）；非影像為 0'),
    sa.Column('height', sa.Integer(), nullable=False, comment='影像高度（px）；非影像為 0'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='影音長度（秒）；靜態圖為 0'),
    sa.Column('project_id', sa.String(length=64), nullable=True, comment='所屬專案 ID；刪除專案時一併清除其素材'),
    sa.Column('source_task_id', sa.String(length=64), nullable=True, comment='產生此檔案的任務 ID；上傳檔案為空'),
    sa.Column('file_metadata', sa.JSON(), nullable=False, comment='額外中繼資料（JSON），如生成參數、種子'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['studio_generation_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_files', schema=None) as batch_op:
        batch_op.create_index('ix_studio_files_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_files_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_studio_files_project_type', ['project_id', 'file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_files_source_task_id'), ['source_task_id'], unique=False)

    op.create_table('studio_generation_tasks',
    sa.Column('id', sa.String(length=64), nullable=False, comment='任務 ID'),
    sa.Column('task_kind', sa.String(length=64), nullable=False, comment='業務任務類型，用於執行器路由'),
    sa.Column('mode', sa.Enum('streaming', 'async_polling', name='taskdeliverymode', native_enum=False, length=32), nullable=False, comment='交付方式'),
    sa.Column('status', sa.Enum('pending', 'running', 'streaming', 'succeeded', 'failed', 'cancelled', name='taskstatus', native_enum=False, length=16), nullable=False, comment='任務狀態'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='進度 0-100'),
    sa.Column('progress_message', sa.String(length=512), nullable=False, comment='目前進行中的步驟描述'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='請求參數（JSON）'),
    sa.Column('result', sa.JSON(), nullable=True, comment='執行結果（JSON）'),
    sa.Column('error', sa.Text(), nullable=False, comment='失敗原因；為空表示無錯誤'),
    sa.Column('error_code', sa.String(length=64), nullable=False, comment='標準化錯誤碼，供前端分支處理'),
    sa.Column('project_id', sa.String(length=64), nullable=True, comment='關聯專案 ID；用於任務中心篩選與回跳'),
    sa.Column('chapter_id', sa.String(length=64), nullable=True, comment='關聯章節 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=True, comment='關聯分鏡 ID'),
    sa.Column('provider_id', sa.String(length=64), nullable=True, comment='執行此任務的供應商 ID'),
    sa.Column('model_id', sa.String(length=64), nullable=True, comment='執行此任務的模型 ID'),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False, comment='是否已請求取消；執行器在安全點偵測此旗標'),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True, comment='請求取消時間'),
    sa.Column('cancel_reason', sa.String(length=255), nullable=False, comment='取消原因'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='實際完成取消的時間'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='開始執行時間'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='結束時間（成功／失敗／取消）'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='已重試次數'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重試次數'),
    sa.Column('executor_type', sa.String(length=32), nullable=False, comment='執行器類型（celery / inline）'),
    sa.Column('executor_task_id', sa.String(length=128), nullable=False, comment='執行器側任務 ID，如 Celery task id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['studio_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['studio_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['studio_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_generation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_generation_tasks_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_generation_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_generation_tasks_shot_id'), ['shot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_generation_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_generation_tasks_task_kind'), ['task_kind'], unique=False)
        batch_op.create_index('ix_studio_tasks_kind_status', ['task_kind', 'status'], unique=False)
        batch_op.create_index('ix_studio_tasks_project_updated', ['project_id', 'updated_at'], unique=False)
        batch_op.create_index('ix_studio_tasks_status_cancel', ['status', 'cancel_requested'], unique=False)
        batch_op.create_index('ix_studio_tasks_status_updated', ['status', 'updated_at'], unique=False)

    op.create_table('studio_projects',
    sa.Column('id', sa.String(length=64), nullable=False, comment='專案 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='專案名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='專案簡介'),
    sa.Column('genre', sa.String(length=64), nullable=False, comment='題材（自由文字，如都市／科幻／古裝）'),
    sa.Column('visual_style', sa.Enum('live_action', 'anime', 'mixed', name='projectvisualstyle', native_enum=False, length=16), nullable=False, comment='畫面表現形式'),
    sa.Column('style_prompt', sa.Text(), nullable=False, comment='專案級風格提示詞；跨鏡頭統一風格的基礎'),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='projectstatus', native_enum=False, length=16), nullable=False, comment='專案狀態'),
    sa.Column('seed', sa.Integer(), nullable=False, comment='生成隨機種子；固定種子有助於跨鏡頭一致性（0 表示不指定）'),
    sa.Column('unify_style', sa.Boolean(), nullable=False, comment='是否在所有章節套用專案級風格'),
    sa.Column('default_video_ratio', sa.String(length=16), nullable=False, comment='預設影片比例；短劇以直式 9:16 為主，分鏡可覆蓋'),
    sa.Column('cover_file_id', sa.String(length=64), nullable=True, comment='封面圖檔案 ID'),
    sa.Column('stats', sa.JSON(), nullable=False, comment='聚合統計（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cover_file_id'], ['studio_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_projects', schema=None) as batch_op:
        batch_op.create_index('ix_studio_projects_status', ['status'], unique=False)
        batch_op.create_index('ix_studio_projects_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_providers',
    sa.Column('id', sa.String(length=64), nullable=False, comment='供應商 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='供應商顯示名稱'),
    sa.Column('kind', sa.Enum('anthropic', 'openai', 'gemini', 'openai_compatible', name='providerkind', native_enum=False, length=32), nullable=False, comment='協定類型，決定使用哪個 Adapter'),
    sa.Column('api_key_env', sa.String(length=128), nullable=False, comment='API 金鑰所在的環境變數名稱；此處絕不存放金鑰值本身'),
    sa.Column('base_url', sa.String(length=1024), nullable=False, comment='文字 API base URL'),
    sa.Column('image_base_url', sa.String(length=1024), nullable=False, comment='圖片 API base URL；留空則沿用 base_url'),
    sa.Column('video_base_url', sa.String(length=1024), nullable=False, comment='影片 API base URL；留空則沿用 base_url'),
    sa.Column('status', sa.Enum('active', 'testing', 'disabled', name='providerstatus', native_enum=False, length=16), nullable=False, comment='啟用狀態'),
    sa.Column('description', sa.Text(), nullable=False, comment='說明'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False, comment='請求逾時（秒）'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='失敗重試次數'),
    sa.Column('extra_config', sa.JSON(), nullable=False, comment='供應商專屬設定（JSON），如 region、api_version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_studio_providers_name')
    )
    with op.batch_alter_table('studio_providers', schema=None) as batch_op:
        batch_op.create_index('ix_studio_providers_kind', ['kind'], unique=False)
        batch_op.create_index('ix_studio_providers_status', ['status'], unique=False)

    op.create_table('studio_shots',
    sa.Column('id', sa.String(length=64), nullable=False, comment='分鏡 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=False, comment='所屬章節 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='鏡頭序號（章節內唯一）'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='鏡頭標題'),
    sa.Column('script_excerpt', sa.Text(), nullable=False, comment='對應的腳本段落'),
    sa.Column('status', sa.Enum('pending', 'ready', name='shotstatus', native_enum=False, length=16), nullable=False, comment='資訊提取確認狀態（非執行時狀態）'),
    sa.Column('skip_extraction', sa.Boolean(), nullable=False, comment='明確跳過提取；為 true 時可直接判定為 ready'),
    sa.Column('last_extracted_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次完成提取的時間；用於區分「尚未提取」與「提取結果為空」'),
    sa.Column('thumbnail_file_id', sa.String(length=64), nullable=True, comment='縮圖檔案 ID'),
    sa.Column('generated_video_file_id', sa.String(length=64), nullable=True, comment='已採用的成品影片檔案 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['studio_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_video_file_id'], ['studio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thumbnail_file_id'], ['studio_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'index', name='uq_studio_shots_chapter_index')
    )
    with op.batch_alter_table('studio_shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_shots_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index('ix_studio_shots_chapter_status', ['chapter_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_shots_generated_video_file_id'), ['generated_video_file_id'], unique=False)
        batch_op.create_index('ix_studio_shots_status', ['status'], unique=False)

    op.create_table('studio_actors',
    sa.Column('gender', sa.String(length=16), nullable=False, comment='性別'),
    sa.Column('age_range', sa.String(length=32), nullable=False, comment='年齡區間'),
    sa.Column('reference_file_id', sa.String(length=64), nullable=True, comment='主要參考圖檔案 ID'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='資產 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='資產名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('appearance_prompt', sa.Text(), nullable=False, comment='外觀提示詞；生成時附加於各鏡頭提示詞以維持一致性'),
    sa.Column('attributes', sa.JSON(), nullable=False, comment='結構化屬性（JSON），各資產類型自行定義'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reference_file_id'], ['studio_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_studio_actors_name')
    )
    with op.batch_alter_table('studio_actors', schema=None) as batch_op:
        batch_op.create_index('ix_studio_actors_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_asset_images',
    sa.Column('id', sa.String(length=64), nullable=False, comment='資產圖片 ID'),
    sa.Column('asset_kind', sa.Enum('character', 'actor', 'scene', 'prop', 'costume', name='assetkind', native_enum=False, length=16), nullable=False, comment='資產類型'),
    sa.Column('asset_id', sa.String(length=64), nullable=False, comment='資產 ID（多型，無外鍵）'),
    sa.Column('file_id', sa.String(length=64), nullable=False, comment='圖片檔案 ID'),
    sa.Column('view_angle', sa.Enum('FRONT', 'LEFT', 'RIGHT', 'BACK', 'THREE_QUARTER', 'TOP', 'DETAIL', name='assetviewangle', native_enum=False, length=16), nullable=False, comment='視角'),
    sa.Column('is_primary', sa.Integer(), nullable=False, comment='是否為主要參考圖（1 是 0 否）；生成時優先採用'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='產生此圖所用的提示詞'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['studio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_asset_images', schema=None) as batch_op:
        batch_op.create_index('ix_studio_asset_images_asset', ['asset_kind', 'asset_id'], unique=False)
        batch_op.create_index('ix_studio_asset_images_asset_angle', ['asset_kind', 'asset_id', 'view_angle'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_asset_images_file_id'), ['file_id'], unique=False)

    op.create_table('studio_file_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用途記錄 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=False, comment='檔案 ID'),
    sa.Column('usage_kind', sa.Enum('shot_frame', 'generated_video', 'asset_image', 'reference_image', 'task_output', 'upload', name='fileusagekind', native_enum=False, length=32), nullable=False, comment='用途類型'),
    sa.Column('owner_type', sa.String(length=32), nullable=False, comment='擁有者類型（多型）'),
    sa.Column('owner_id', sa.String(length=64), nullable=False, comment='擁有者 ID（多型）'),
    sa.Column('note', sa.Text(), nullable=False, comment='補充說明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['studio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_file_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_file_usages_file_id'), ['file_id'], unique=False)
        batch_op.create_index('ix_studio_file_usages_file_kind', ['file_id', 'usage_kind'], unique=False)
        batch_op.create_index('ix_studio_file_usages_owner', ['owner_type', 'owner_id'], unique=False)

    op.create_table('studio_generation_task_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='關聯行 ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任務 ID'),
    sa.Column('resource_type', sa.String(length=32), nullable=False, comment='產出資源類型（image / video / text）'),
    sa.Column('relation_type', sa.String(length=32), nullable=False, comment='業務類型（shot_frame / character / prop 等）'),
    sa.Column('relation_entity_id', sa.String(length=64), nullable=False, comment='業務實體 ID（多型，無外鍵）'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='產出檔案 ID'),
    sa.Column('status', sa.Enum('todo', 'accepted', 'rejected', name='tasklinkstatus', native_enum=False, length=16), nullable=False, comment='採用狀態'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['studio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['studio_generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'resource_type', 'relation_type', 'relation_entity_id', 'file_id', name='uq_studio_task_links_task_resource_entity_file')
    )
    with op.batch_alter_table('studio_generation_task_links', schema=None) as batch_op:
        batch_op.create_index('ix_studio_task_links_file', ['file_id'], unique=False)
        batch_op.create_index('ix_studio_task_links_relation', ['relation_type', 'relation_entity_id'], unique=False)
        batch_op.create_index('ix_studio_task_links_status_updated', ['status', 'updated_at'], unique=False)

    op.create_table('studio_models',
    sa.Column('id', sa.String(length=64), nullable=False, comment='模型設定 ID'),
    sa.Column('provider_id', sa.String(length=64), nullable=False, comment='所屬供應商 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='顯示名稱'),
    sa.Column('model_id', sa.String(length=255), nullable=False, comment='供應商端的實際模型識別碼，例如 claude-opus-5'),
    sa.Column('category', sa.Enum('text', 'image', 'video', name='modelcategory', native_enum=False, length=16), nullable=False, comment='模型類別'),
    sa.Column('enabled', sa.Integer(), nullable=False, comment='是否啟用（1 是 0 否）'),
    sa.Column('params', sa.JSON(), nullable=False, comment='預設呼叫參數（JSON），如 temperature、max_tokens、size'),
    sa.Column('description', sa.Text(), nullable=False, comment='說明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['studio_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', 'category', name='uq_studio_models_provider_model_category')
    )
    with op.batch_alter_table('studio_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_models_category'), ['category'], unique=False)
        batch_op.create_index('ix_studio_models_category_enabled', ['category', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_models_provider_id'), ['provider_id'], unique=False)

    op.create_table('studio_prompt_templates',
    sa.Column('id', sa.String(length=64), nullable=False, comment='模板 ID'),
    sa.Column('category', sa.Enum('frame_first_image', 'frame_last_image', 'frame_key_image', 'video_prompt', 'storyboard_prompt', 'character_image', 'actor_image', 'scene_image', 'prop_image', 'costume_image', 'script_divide', 'script_extract', 'script_optimize', 'script_simplify', 'script_consistency', name='promptcategory', native_enum=False, length=32), nullable=False, comment='模板類別'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模板名稱'),
    sa.Column('content', sa.Text(), nullable=False, comment='模板內容，含 {變數} 佔位'),
    sa.Column('description', sa.Text(), nullable=False, comment='說明'),
    sa.Column('is_default', sa.Integer(), nullable=False, comment='是否為該類別的預設模板（1 是 0 否）'),
    sa.Column('project_id', sa.String(length=64), nullable=True, comment='所屬專案 ID；為空表示全域模板'),
    sa.Column('variables', sa.JSON(), nullable=False, comment='模板可用變數名稱清單（JSON），供前端提示'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_prompt_templates_category'), ['category'], unique=False)
        batch_op.create_index('ix_studio_prompt_templates_category_default', ['category', 'is_default'], unique=False)
        batch_op.create_index('ix_studio_prompt_templates_project_category', ['project_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_prompt_templates_project_id'), ['project_id'], unique=False)

    op.create_table('studio_props',
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所屬專案 ID'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='道具分類'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='資產 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='資產名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('appearance_prompt', sa.Text(), nullable=False, comment='外觀提示詞；生成時附加於各鏡頭提示詞以維持一致性'),
    sa.Column('attributes', sa.JSON(), nullable=False, comment='結構化屬性（JSON），各資產類型自行定義'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_studio_props_project_name')
    )
    with op.batch_alter_table('studio_props', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_props_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_studio_props_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_scenes',
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所屬專案 ID'),
    sa.Column('location_type', sa.String(length=32), nullable=False, comment='場地類型（室內／室外）'),
    sa.Column('time_of_day', sa.String(length=32), nullable=False, comment='時間（日／夜／黃昏）'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='資產 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='資產名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('appearance_prompt', sa.Text(), nullable=False, comment='外觀提示詞；生成時附加於各鏡頭提示詞以維持一致性'),
    sa.Column('attributes', sa.JSON(), nullable=False, comment='結構化屬性（JSON），各資產類型自行定義'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_studio_scenes_project_name')
    )
    with op.batch_alter_table('studio_scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_scenes_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_studio_scenes_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_shot_asset_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='關聯行 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='分鏡 ID'),
    sa.Column('asset_kind', sa.Enum('character', 'actor', 'scene', 'prop', 'costume', name='assetkind', native_enum=False, length=16), nullable=False, comment='資產類型'),
    sa.Column('asset_id', sa.String(length=64), nullable=False, comment='資產 ID（多型，無外鍵）'),
    sa.Column('index', sa.Integer(), nullable=False, comment='出場順序；角色用於決定提示詞中的主次'),
    sa.Column('note', sa.Text(), nullable=False, comment='此鏡頭中的特殊說明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'asset_kind', 'asset_id', name='uq_studio_shot_asset_links_shot_asset')
    )
    with op.batch_alter_table('studio_shot_asset_links', schema=None) as batch_op:
        batch_op.create_index('ix_studio_shot_asset_links_asset', ['asset_kind', 'asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_shot_asset_links_shot_id'), ['shot_id'], unique=False)

    op.create_table('studio_shot_candidates',
    sa.Column('id', sa.String(length=64), nullable=False, comment='候選 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='所屬分鏡 ID'),
    sa.Column('candidate_type', sa.Enum('character', 'scene', 'prop', 'costume', name='shotcandidatetype', native_enum=False, length=16), nullable=False, comment='候選資產類型'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='提取出的名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='提取出的描述'),
    sa.Column('status', sa.Enum('pending', 'linked', 'ignored', name='shotcandidatestatus', native_enum=False, length=16), nullable=False, comment='確認狀態'),
    sa.Column('linked_entity_id', sa.String(length=64), nullable=True, comment='確認後連結到的資產 ID；跨多張資產表，故不設外鍵'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'candidate_type', 'name', name='uq_studio_shot_candidates_shot_type_name')
    )
    with op.batch_alter_table('studio_shot_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_shot_candidates_shot_id'), ['shot_id'], unique=False)
        batch_op.create_index('ix_studio_shot_candidates_status', ['shot_id', 'status'], unique=False)

    op.create_table('studio_shot_dialogue_candidates',
    sa.Column('id', sa.String(length=64), nullable=False, comment='對白候選 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='所屬分鏡 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='對白順序'),
    sa.Column('speaker_name', sa.String(length=255), nullable=False, comment='提取出的說話者'),
    sa.Column('content', sa.Text(), nullable=False, comment='提取出的對白內容'),
    sa.Column('mode', sa.Enum('DIALOGUE', 'VOICE_OVER', 'OFF_SCREEN', 'PHONE', name='dialoguelinemode', native_enum=False, length=16), nullable=False, comment='對白模式'),
    sa.Column('status', sa.Enum('pending', 'accepted', 'ignored', name='shotdialoguecandidatestatus', native_enum=False, length=16), nullable=False, comment='確認狀態'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'index', name='uq_studio_shot_dialogue_candidates_shot_index')
    )
    with op.batch_alter_table('studio_shot_dialogue_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_shot_dialogue_candidates_shot_id'), ['shot_id'], unique=False)
        batch_op.create_index('ix_studio_shot_dialogue_candidates_status', ['shot_id', 'status'], unique=False)

    op.create_table('studio_shot_frames',
    sa.Column('id', sa.String(length=64), nullable=False, comment='幀 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='所屬分鏡 ID'),
    sa.Column('frame_type', sa.Enum('first', 'last', 'key', name='shotframetype', native_enum=False, length=16), nullable=False, comment='幀類型'),
    sa.Column('index', sa.Integer(), nullable=False, comment='同類型內的序號'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='該幀的圖片生成提示詞'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='已採用的圖片檔案 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['studio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'frame_type', 'index', name='uq_studio_shot_frames_shot_type_index')
    )
    with op.batch_alter_table('studio_shot_frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_shot_frames_shot_id'), ['shot_id'], unique=False)
        batch_op.create_index('ix_studio_shot_frames_shot_type', ['shot_id', 'frame_type'], unique=False)

    op.create_table('studio_characters',
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所屬專案 ID'),
    sa.Column('actor_id', sa.String(length=64), nullable=True, comment='綁定的演員 ID；決定該角色的視覺形象'),
    sa.Column('role_type', sa.String(length=32), nullable=False, comment='角色定位（主角／配角／龍套等）'),
    sa.Column('personality', sa.Text(), nullable=False, comment='性格描述'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='資產 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='資產名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('appearance_prompt', sa.Text(), nullable=False, comment='外觀提示詞；生成時附加於各鏡頭提示詞以維持一致性'),
    sa.Column('attributes', sa.JSON(), nullable=False, comment='結構化屬性（JSON），各資產類型自行定義'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['studio_actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_studio_characters_project_name')
    )
    with op.batch_alter_table('studio_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_characters_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_characters_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_studio_characters_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_model_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='設定行 ID（固定為 1）'),
    sa.Column('default_text_model_id', sa.String(length=64), nullable=True, comment='預設文字模型 ID'),
    sa.Column('default_image_model_id', sa.String(length=64), nullable=True, comment='預設圖片模型 ID'),
    sa.Column('default_video_model_id', sa.String(length=64), nullable=True, comment='預設影片模型 ID'),
    sa.Column('task_defaults', sa.JSON(), nullable=False, comment='各任務類型的預設模型覆蓋（JSON：task_kind -> model_id）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_image_model_id'], ['studio_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_text_model_id'], ['studio_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_video_model_id'], ['studio_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio_shot_details',
    sa.Column('id', sa.String(length=64), nullable=False, comment='分鏡 ID（與 studio_shots.id 共享主鍵）'),
    sa.Column('camera_shot', sa.Enum('ECU', 'CU', 'MCU', 'MS', 'MLS', 'LS', 'ELS', name='camerashottype', native_enum=False, length=16), nullable=False, comment='景別'),
    sa.Column('angle', sa.Enum('EYE_LEVEL', 'HIGH_ANGLE', 'LOW_ANGLE', 'BIRD_EYE', 'DUTCH', 'OVER_SHOULDER', name='cameraangle', native_enum=False, length=16), nullable=False, comment='機位角度'),
    sa.Column('movement', sa.Enum('STATIC', 'PAN', 'TILT', 'DOLLY_IN', 'DOLLY_OUT', 'TRACK', 'CRANE', 'HANDHELD', 'STEADICAM', 'ZOOM_IN', 'ZOOM_OUT', name='cameramovement', native_enum=False, length=16), nullable=False, comment='運鏡方式'),
    sa.Column('scene_id', sa.String(length=64), nullable=True, comment='關聯場景 ID'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='鏡頭時長（秒）；影片生成的唯一時長來源'),
    sa.Column('override_video_ratio', sa.String(length=16), nullable=True, comment='分鏡級影片比例覆蓋；為空表示繼承專案預設'),
    sa.Column('description', sa.Text(), nullable=False, comment='鏡頭整體描述'),
    sa.Column('action_beats', sa.JSON(), nullable=False, comment='動作節拍（JSON 陣列）；影片生成時轉為時序描述'),
    sa.Column('mood_tags', sa.JSON(), nullable=False, comment='情緒標籤（JSON 陣列）'),
    sa.Column('atmosphere', sa.Text(), nullable=False, comment='氛圍描述'),
    sa.Column('vfx_type', sa.Enum('NONE', 'PARTICLES', 'VOLUMETRIC_FOG', 'CG_DOUBLE', 'DIGITAL_ENVIRONMENT', 'MATTE_PAINTING', 'FIRE_SMOKE', 'WATER_SIM', 'DESTRUCTION', 'ENERGY_MAGIC', 'COMPOSITING_CLEANUP', 'SLOW_MOTION_TIME', 'OTHER', name='vfxtype', native_enum=False, length=32), nullable=False, comment='視效類型'),
    sa.Column('vfx_note', sa.Text(), nullable=False, comment='視效說明'),
    sa.Column('has_bgm', sa.Boolean(), nullable=False, comment='是否包含 BGM'),
    sa.Column('video_prompt', sa.Text(), nullable=False, comment='影片生成提示詞；由模板與鏡頭資料組出後可人工修改'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['studio_scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_shot_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_shot_details_scene_id'), ['scene_id'], unique=False)

    op.create_table('studio_costumes',
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所屬專案 ID'),
    sa.Column('character_id', sa.String(length=64), nullable=True, comment='預設穿著此服裝的角色 ID'),
    sa.Column('season', sa.String(length=32), nullable=False, comment='season／場合'),
    sa.Column('id', sa.String(length=64), nullable=False, comment='資產 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='資產名稱'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('appearance_prompt', sa.Text(), nullable=False, comment='外觀提示詞；生成時附加於各鏡頭提示詞以維持一致性'),
    sa.Column('attributes', sa.JSON(), nullable=False, comment='結構化屬性（JSON），各資產類型自行定義'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['studio_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['studio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_studio_costumes_project_name')
    )
    with op.batch_alter_table('studio_costumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_costumes_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_costumes_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_studio_costumes_updated_at', ['updated_at'], unique=False)

    op.create_table('studio_shot_dialogues',
    sa.Column('id', sa.String(length=64), nullable=False, comment='對白 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='所屬分鏡 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='對白順序'),
    sa.Column('character_id', sa.String(length=64), nullable=True, comment='說話角色 ID；旁白可為空'),
    sa.Column('speaker_name', sa.String(length=255), nullable=False, comment='說話者名稱；角色尚未建立時的暫存值'),
    sa.Column('content', sa.Text(), nullable=False, comment='對白內容'),
    sa.Column('mode', sa.Enum('DIALOGUE', 'VOICE_OVER', 'OFF_SCREEN', 'PHONE', name='dialoguelinemode', native_enum=False, length=16), nullable=False, comment='對白模式'),
    sa.Column('emotion', sa.String(length=64), nullable=False, comment='情緒提示'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['studio_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['studio_shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'index', name='uq_studio_shot_dialogues_shot_index')
    )
    with op.batch_alter_table('studio_shot_dialogues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_shot_dialogues_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_shot_dialogues_shot_id'), ['shot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滾變更。"""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_shot_dialogues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_shot_dialogues_shot_id'))
        batch_op.drop_index(batch_op.f('ix_studio_shot_dialogues_character_id'))

    op.drop_table('studio_shot_dialogues')
    with op.batch_alter_table('studio_costumes', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_costumes_updated_at')
        batch_op.drop_index(batch_op.f('ix_studio_costumes_project_id'))
        batch_op.drop_index(batch_op.f('ix_studio_costumes_character_id'))

    op.drop_table('studio_costumes')
    with op.batch_alter_table('studio_shot_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_shot_details_scene_id'))

    op.drop_table('studio_shot_details')
    op.drop_table('studio_model_settings')
    with op.batch_alter_table('studio_characters', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_characters_updated_at')
        batch_op.drop_index(batch_op.f('ix_studio_characters_project_id'))
        batch_op.drop_index(batch_op.f('ix_studio_characters_actor_id'))

    op.drop_table('studio_characters')
    with op.batch_alter_table('studio_shot_frames', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_shot_frames_shot_type')
        batch_op.drop_index(batch_op.f('ix_studio_shot_frames_shot_id'))

    op.drop_table('studio_shot_frames')
    with op.batch_alter_table('studio_shot_dialogue_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_shot_dialogue_candidates_status')
        batch_op.drop_index(batch_op.f('ix_studio_shot_dialogue_candidates_shot_id'))

    op.drop_table('studio_shot_dialogue_candidates')
    with op.batch_alter_table('studio_shot_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_shot_candidates_status')
        batch_op.drop_index(batch_op.f('ix_studio_shot_candidates_shot_id'))

    op.drop_table('studio_shot_candidates')
    with op.batch_alter_table('studio_shot_asset_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_shot_asset_links_shot_id'))
        batch_op.drop_index('ix_studio_shot_asset_links_asset')

    op.drop_table('studio_shot_asset_links')
    with op.batch_alter_table('studio_scenes', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_scenes_updated_at')
        batch_op.drop_index(batch_op.f('ix_studio_scenes_project_id'))

    op.drop_table('studio_scenes')
    with op.batch_alter_table('studio_props', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_props_updated_at')
        batch_op.drop_index(batch_op.f('ix_studio_props_project_id'))

    op.drop_table('studio_props')
    with op.batch_alter_table('studio_prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_prompt_templates_project_id'))
        batch_op.drop_index('ix_studio_prompt_templates_project_category')
        batch_op.drop_index('ix_studio_prompt_templates_category_default')
        batch_op.drop_index(batch_op.f('ix_studio_prompt_templates_category'))

    op.drop_table('studio_prompt_templates')
    with op.batch_alter_table('studio_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_models_provider_id'))
        batch_op.drop_index('ix_studio_models_category_enabled')
        batch_op.drop_index(batch_op.f('ix_studio_models_category'))

    op.drop_table('studio_models')
    with op.batch_alter_table('studio_generation_task_links', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_task_links_status_updated')
        batch_op.drop_index('ix_studio_task_links_relation')
        batch_op.drop_index('ix_studio_task_links_file')

    op.drop_table('studio_generation_task_links')
    with op.batch_alter_table('studio_file_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_file_usages_owner')
        batch_op.drop_index('ix_studio_file_usages_file_kind')
        batch_op.drop_index(batch_op.f('ix_studio_file_usages_file_id'))

    op.drop_table('studio_file_usages')
    with op.batch_alter_table('studio_asset_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_asset_images_file_id'))
        batch_op.drop_index('ix_studio_asset_images_asset_angle')
        batch_op.drop_index('ix_studio_asset_images_asset')

    op.drop_table('studio_asset_images')
    with op.batch_alter_table('studio_actors', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_actors_updated_at')

    op.drop_table('studio_actors')
    with op.batch_alter_table('studio_shots', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_shots_status')
        batch_op.drop_index(batch_op.f('ix_studio_shots_generated_video_file_id'))
        batch_op.drop_index('ix_studio_shots_chapter_status')
        batch_op.drop_index(batch_op.f('ix_studio_shots_chapter_id'))

    op.drop_table('studio_shots')
    with op.batch_alter_table('studio_providers', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_providers_status')
        batch_op.drop_index('ix_studio_providers_kind')

    op.drop_table('studio_providers')
    with op.batch_alter_table('studio_projects', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_projects_updated_at')
        batch_op.drop_index('ix_studio_projects_status')

    op.drop_table('studio_projects')
    with op.batch_alter_table('studio_generation_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_tasks_status_updated')
        batch_op.drop_index('ix_studio_tasks_status_cancel')
        batch_op.drop_index('ix_studio_tasks_project_updated')
        batch_op.drop_index('ix_studio_tasks_kind_status')
        batch_op.drop_index(batch_op.f('ix_studio_generation_tasks_task_kind'))
        batch_op.drop_index(batch_op.f('ix_studio_generation_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_studio_generation_tasks_shot_id'))
        batch_op.drop_index(batch_op.f('ix_studio_generation_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_studio_generation_tasks_chapter_id'))

    op.drop_table('studio_generation_tasks')
    with op.batch_alter_table('studio_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_files_source_task_id'))
        batch_op.drop_index('ix_studio_files_project_type')
        batch_op.drop_index(batch_op.f('ix_studio_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_studio_files_file_type'))
        batch_op.drop_index('ix_studio_files_created_at')

    op.drop_table('studio_files')
    with op.batch_alter_table('studio_chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_chapters_updated_at')
        batch_op.drop_index('ix_studio_chapters_status')
        batch_op.drop_index(batch_op.f('ix_studio_chapters_project_id'))

    op.drop_table('studio_chapters')
    # ### end Alembic commands ###
